name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
        
      - name: Build js version
        run: deno task ts2js

      - name: Replace .ts with .js
        run: deno task changeExtension

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish ./npm --provenance --access public 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
